---
title: "ch_6_walkthrough"
output: html_document
---

```{r Load libraries and data, message=FALSE, warning=FALSE}
library(tidyverse)
library(dataedu)
library(skimr)
library(janitor)

dataedu::ma_data_init
dataedu::ma_data_init -> ma_data
ma_data_init <- dataedu::ma_data_init
```

```{r Exploring and manipulating your data}
# Exploring and manipulating your data
names(ma_data_init)

glimpse(ma_data_init)

summary(ma_data_init)

glimpse(ma_data_init$Town)

summary(ma_data_init$Town)

glimpse(ma_data_init$`AP_Test Takers`)

summary(ma_data_init$`AP_Test Takers`)

```
```{r Exploring and manipulating your data2}
# ma_data_init %>% 
#   group_by(District Name) %>% 
#   count()

ma_data_init %>% 
  group_by(`District Name`) %>% 
  count()

ma_data_init %>% 
  group_by(`District Name`) %>% 
  count() %>% 
  filter(n > 10)

ma_data_init %>% 
  group_by(`District Name`) %>% 
  count() %>% 
  filter(n > 10) %>% 
  arrange(desc(n))

# ma_data_init %>% 
#   group_by(`District Name`) %>% 
#   count() %>% 
#   filter(n = 10)

ma_data_init %>% 
  group_by(`District Name`) %>% 
  count() %>% 
  filter(n == 10)

ma_data_init %>% 
  rename(district_name = `District Name`,
         grade = Grade) %>% 
  select(district_name, grade)

```

```{r Exploring and manipulating your data3}
#clean_names is part of the janitor package

# ma data <-
#   ma_data_init %>% 
#   clean_names()

# 01_ma_data <-
#   ma_data_init %>% 
#   clean_names()

ma_data_01 <-
  ma_data_init %>% 
  clean_names()

MA_data_02 <-
  ma_data_init %>% 
  clean_names()

```

