---
title: "ch_7_walkthrough"
output: html_document
---


```{r Load Libraries & Data, message=FALSE, warning=FALSE}
library(tidyverse)
library(apaTables)
library(sjPlot)
library(readxl)
library(dataedu)


# Pre-survey for the F15 and S16 semesters

pre_survey <- dataedu::pre_survey

# Gradebook and log-trace data for F15 and S16 semesters

course_data <- dataedu::course_data

# Log-trace data for F15 and S16 semesters - this is for time spent

course_minutes <- dataedu::course_minutes

```

```{r Survey - Data Formatting - Column Name Change}
pre_survey  <-
  pre_survey  %>%
  # Rename the qustions something easier to work with because R is case sensitive
  # and working with variable names in mix case is prone to error
  rename(
    q1 = Q1MaincellgroupRow1,
    q2 = Q1MaincellgroupRow2,
    q3 = Q1MaincellgroupRow3,
    q4 = Q1MaincellgroupRow4,
    q5 = Q1MaincellgroupRow5,
    q6 = Q1MaincellgroupRow6,
    q7 = Q1MaincellgroupRow7,
    q8 = Q1MaincellgroupRow8,
    q9 = Q1MaincellgroupRow9,
    q10 = Q1MaincellgroupRow10
  ) %>%
  # Convert all question responses to numeric
  mutate_at(vars(q1:q10), list( ~ as.numeric(.)))

```


```{r Survey - Data Formatting - Scale Reverse}

# This part of the code is where we write the function:
# Function for reversing scales 
reverse_scale <- function(question) {
  # Reverses the response scales for consistency
  #   Arguments:
  #     question - survey question
  #   Returns: 
  #    a numeric converted response
  # Note: even though 3 is not transformed, case_when expects a match for all
  # possible conditions, so it's best practice to label each possible input
  # and use TRUE ~ as the final statement returning NA for unexpected inputs
  x <- case_when(
    question == 1 ~ 5,
    question == 2 ~ 4,
    question == 3 ~ 3, 
    question == 4 ~ 2,
    question == 5 ~ 1,
    TRUE ~ NA_real_
  )
  x
}

# And here's where we use that function to reverse the scales
# We use the pipe operator %>% here
# Reverse scale for questions 4 and 7
pre_survey <-
  pre_survey %>%
  mutate(q4 = reverse_scale(q4),
         q7 = reverse_scale(q7))

```



```{r Survey - Data Formatting - Wide to Long Format}
# Pivot the dataset from wide to long format
measure_mean <-
  pre_survey %>%
  # Gather questions and responses
  pivot_longer(cols = q1:q10,
               names_to = "question",
               values_to = "response")

```

```{r Survey - Data Formatting - Relate Question Number to Category}
# Add measure variable 
measure_mean <- measure_mean %>% 
  # Here's where we make the column of question categories called "measure"
  mutate(
    measure = case_when(
      question %in% c("q1", "q4", "q5", "q8", "q10") ~ "int",
      question %in% c("q2", "q6", "q9") ~ "uv",
      question %in% c("q3", "q7") ~ "pc",
      TRUE ~ NA_character_)
  )

```

```{r Survey - Data Formatting - Create new set Grouped}
# my note: I don't particularly like how they overwite measure_mean with the group. I thought they would create an entirely new set with a different name while keeping the measure_mean set. That is what I would have done.

# Add measure variable 
measure_mean <- measure_mean %>%
  # First, we group by the new variable "measure"
  group_by(measure) %>%
  # Here's where we compute the mean of the responses
  summarize(
    # Creating a new variable to indicate the mean response for each measure
    mean_response = mean(response, na.rm = TRUE),
    # Creating a new variable to indicate the percent of each measure that 
    # had NAs in the response field
    percent_NA = mean(is.na(response))
    )

measure_mean

```
```{r course_data - Data Formatting - Separate CourseID into 3 Columns}
# split course section into components
course_data <- 
  course_data %>%
  # Give course subject, semester, and section their own columns
  separate(
    col = CourseSectionOrigID,
    into = c("subject", "semester", "section"),
    sep = "-",
    remove = FALSE
  )

```

```{r course_data - Data Formatting - Renaming Columns to Match two datasets}
#In order to combine course_data set with pre_survey set, we must rename the columns for studentID and courseID so that they match in each data set
pre_survey <-
  pre_survey %>%
  rename(student_id = opdata_username,
         course_id = opdata_CourseID)

pre_survey

#Using str_sub() from the stringr package to clean up student_id column
# Re-create the variable "student_id" so that it excludes the extraneous characters
pre_survey <- pre_survey %>% 
  mutate(student_id = str_sub(student_id, start = 2, end = -3)) #minues 3 means start from the right side. 3 because it is the placement of the first character we want to INCLUDE

# Save the new variable as numeric so that R no longer thinks it is text 
pre_survey <- pre_survey %>% 
  mutate(student_id = as.numeric(student_id))

course_data <-
  course_data %>%
  rename(student_id = Bb_UserPK,
         course_id = CourseSectionOrigID)

```

```{r course_data - Data Formatting - Join the datasets}
#all rows in course_data are retained with matching rows of pre_survey added on
dat <-
  left_join(course_data, pre_survey,
            by = c("student_id", "course_id"))
dat

#retains all matching rows in the "left" and "right data sets
dat_semi <- 
  semi_join(course_data,pre_survey,
            by = c("student_id", "course_id"))

dat_semi


#removes all rows in the "left" that can be joined with those on the "right"
dat_anti <-
  anti_join(course_data,
            pre_survey,
            by = c("student_id", "course_id"))

dat_anti

#opposite of left join, keeps all rows from the "right" data set
dat_right <-
  right_join(course_data,
             pre_survey,
             by = c("student_id", "course_id"))

dat_right
```

```{r course_minutes - Data Formatting - Cleanup and Join}
course_minutes <-
  course_minutes %>%
  rename(student_id = Bb_UserPK,
         course_id = CourseSectionOrigID)

course_minutes <-
  course_minutes %>%
  # Change the data type for student_id in course_minutes so we can match to 
  # student_id in dat
  mutate(student_id = as.integer(student_id))

dat <- 
  dat %>% 
  left_join(course_minutes, 
            by = c("student_id", "course_id"))
```

```{r Data Formatting - Finding distinct cases}
glimpse(dat)

distinct(dat, Gradebook_Item)

distinct(dat, course_id, Gradebook_Item)

#we only want one row for each student in the course. Analyzing at the student level and not specific gradebook item level
dat <-
  distinct(dat, course_id, student_id, .keep_all = TRUE)

dat <- rename(dat, final_grade = FinalGradeCEMS)
```

